Added 'settings' to properties in README
Esri/application-base-js pull request #7
Opened 2017-04-27 20:31 UTC by MikeTschudi

2017-04-27 20:41 UTC, driskull requested changes

2017-04-27 20:41 UTC, driskull commented on README.MD
> +|results|ApplicationBase query results|[ApplicationBaseConfig](#applicationbaseconfig)|true|
These ones don't seem right. It should be `ApplicationBaseResults` for results and settings needs a new definition

2017-04-28 16:04 UTC, MikeTschudi commented
It's not correct; I'm sorry.  Thanks for the catch--I'd switched `results` and `settings`.

2017-04-28 16:16 UTC, driskull approved these changes
thanks! looks good

2017-04-28 16:16 UTC, merged